pool:
  vmImage: 'vs2017-win2016'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- pwsh: |
    New-Item -ItemType "directory" -Path $(GOBIN)
    New-Item -ItemType "directory" -Path $(GOPATH)/pkg
    New-Item -ItemType "directory" -Path $(modulePath)/pkg
    Move-Item -Path $(system.defaultWorkingDirectory)\*.* -Destination $(modulePath)
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'
