pool:
  vmImage: 'vs2017-win2016'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '$(GOROOT_1_11_X64)' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)\gopath' # Go workspace path
  modulePath: '$(GOPATH)\src\github.com\$(build.repository.name)' # Path to the module's code

steps:
- pwsh: |
    New-Item -ItemType "directory" -Path $(GOBIN)
    New-Item -ItemType "directory" -Path $(GOPATH)\pkg
    New-Item -ItemType "directory" -Path $(modulePath)\pkg
    Move-Item -Path $(system.defaultWorkingDirectory)\*.* -Destination $(modulePath)
    $env:Path += ";$(GOBIN)"
    $env:Path += ";$(GOROOT)\bin"
  displayName: 'Set up the Go workspace'

- pwsh: |
  choco install dep
  dep ensure
  workingDirectory: '$(modulePath)'
  displayName: 'Install and run dep'
