strategy:
  matrix:
    UnitTest:
      TESTKIND: "unit"
    IntegrationTest:
      TESTKIND: "integration"

pool:
  vmImage: 'vs2017-win2016'

variables:
  GOPATH: '$(system.defaultWorkingDirectory)\gopath' # Go workspace path
  modulePath: '$(GOPATH)\src\github.com\$(build.repository.name)' # Path to the module's code
  TERRAFORMVERSION: 0.11.13

steps:
- pwsh: |
    New-Item -ItemType "directory" -Path $(GOPATH)\pkg
    New-Item -ItemType "directory" -Path $(modulePath)
    Get-ChildItem -Path $(system.defaultWorkingDirectory) -Exclude gopath | Move-Item -Destination $(modulePath)
  displayName: 'Set up the Go workspace'

- script: choco install dep
  displayName: 'Install dep'

- script: choco install terraform --version $(TERRAFORMVERSION)
  displayName: 'Install Terraform'

- script: dep ensure
  workingDirectory: '$(modulePath)'
  displayName: 'Run `dep ensure`'

- pwsh: |
    if ("$(TESTKIND)" -eq "unit") {
      go test -v -parallel 1 $(go list ./... | where-object { $_ -notlike "*/test" })
    }

    if ("$(TESTKIND)" -eq "integration") {
      go test -v $(go list ./... | where-object { $_ -like "*/test" })
    }
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'