pool:
  vmImage: 'vs2017-win2016'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- pwsh: |
    New-Item -ItemType "directory" -Path $env:GOBIN
    New-Item -ItemType "directory" -Path $env:GOPATH/pkg
    New-Item -ItemType "directory" -Path $env:modulePath/pkg
    Move-Item -Path $(system.defaultWorkingDirectory)\*.* -Destination $env:modulePath
    Write-Host '##vso[task.prependpath]$env:GOBIN'
    Write-Host '##vso[task.prependpath]$env:GOROOT/bin'
  displayName: 'Set up the Go workspace'
